### ISSUE TITLE
File not found 

### ISSUE THREAD

**Issue by sahilmo** [saravanastar/video-streaming#1]
When hitting url this error showing 
![Screen Shot 2020-04-22 at 12 29 21 PM](https://user-images.githubusercontent.com/33277064/79959395-25f49180-8495-11ea-955e-6d1302c41433.png)

**Comment by saravanastar** [comment]
Thanks for reporting it.Pull the latest from the master and try now. I haven't faced any issue but changed the logic. Let me know once after that.

**Comment by sahilmo** [comment]
> 
> 
> Thanks for reporting it.Pull the latest from the master and try now. I haven't faced any issue but changed the logic. Let me know once after that.

I tried still same. Path not reading

**Comment by saravanastar** [comment]
can you check your target folder
![image](https://user-images.githubusercontent.com/14228896/80007718-a961b300-8494-11ea-929f-8b86fc792d8f.png)

**Comment by saravanastar** [comment]
> > Thanks for reporting it.Pull the latest from the master and try now. I haven't faced any issue but changed the logic. Let me know once after that.
> 
> I tried still same. Path not reading

Can you check the target folder

![image](https://user-images.githubusercontent.com/14228896/80007797-ca2a0880-8494-11ea-8fe9-182bae86570f.png)

**Comment by testteuno** [comment]
Don't know if it matters, but if you run it on windows where one of the folders in the path has a space (%20) the mp4 will not read.
